version: 2
updates:
  # Maintain dependencies for Rust (Cargo)
  - package-ecosystem: "cargo"
    commit-message:
      include: scope
      prefix: bump
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    commit-message:
      include: scope
      prefix: bump
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3

  # Maintain dependencies for GitHub Action
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    commit-message:
      include: scope
      prefix: bump
    directory: "/web"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
