name: Lint
on:
  pull_request:
    types:
      - opened
      - edited # Only the title job needs this, other jobs skip it
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  contents: read # To checkout
  pull-requests: write # To comment to PRs

jobs:
  actionlint:
    name: actionlint
    if: github.event.action != 'edited'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: reviewdog/action-actionlint@dbe5299849118fd6f099ba563d263d770955a64a # v1.73.2
        with:
          reporter: github-pr-review

  alex:
    if: github.event.action != 'edited'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: reviewdog/action-alex@347481655add010a2ae302df34b57c9bcfa0d6e4 # v1.17.0
        with:
          reporter: github-pr-review

  assign-author:
    if: github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@a78a94b219445cece8ccf0d45fec60af449f212a # v3.1.0

  clippy:
    if: github.event.action != 'edited'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2

      - uses: sksat/action-clippy@87e08e0c289f2654fe702b0aaf88c2f1027a3e57 # v1.1.1
        with:
          reporter: github-pr-review

  markdown:
    name: markdown
    if: github.event.action != 'edited'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: reviewdog/action-markdownlint@6f0e0e8703a9e840ffefa37a2775832c51c1c640 # v0.28.0
        with:
          level: warning
          markdownlint_flags: website/docs/**/*.md
          reporter: github-pr-review

  misspell:
    name: misspell
    if: github.event.action != 'edited'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: reviewdog/action-misspell@d6429416b12b09b4e2768307d53bef58d172e962 # v1.27.0
        with:
          level: warning
          reporter: github-pr-review

  title:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          disallowScopes: |
            release
            [A-Z]+
          requireScope: true
          subjectPattern: ^(?![A-Z]).+$
          scopes: |
            .github
            cli
            deps
            other
            web
          types: |
            bump
            chore
            doc
            feat
            fix
