name: Lint
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

permissions:
  contents: read # To checkout
  pull-requests: write # To comment to PRs

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-pr-review

  alex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: reviewdog/action-alex@v1
        with:
          reporter: github-pr-review

  assign-author:
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@v1.6.2

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - uses: actions-rs/cargo@v1
        with:
          command: clippy

      - uses: sksat/action-clippy@v1.0.0
        with:
          reporter: github-pr-review

  markdown:
    name: markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-markdownlint@v0
        with:
          level: warning
          markdownlint_flags: website/docs/**/*.md
          reporter: github-pr-review

  misspell:
    name: misspell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: reviewdog/action-misspell@v1
        with:
          level: warning
          reporter: github-pr-review

  title:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          disallowScopes: |
            release
            [A-Z]+
          requireScope: true
          subjectPattern: ^(?![A-Z]).+$
          scopes: |
            .github
            cli
            deps
            other
            web
          types: |
            bump
            chore
            doc
            feat
            fix
